version: '3.8'

services:

  auth:
    restart: always
    build: ./auth
    depends_on:
      - db
    environment:
      DB_HOST: db                 # Use 'db' to connect to the local PostgreSQL container
      DB_PORT: 5432               # default PostgreSQL port
      DB_USER: adminesraa
      DB_PASSWORD: MySecretPassword
      DB_NAME: weatherapp
    ports:
      - "8080:8080"               # expose for local testing
    networks:
      - app-net

  ui:
    restart: always
    build: ./UI
    depends_on:
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "3000:3000"
    networks:
      - app-net

  weather:
    restart: always
    build: ./weather
    environment:
      APIKEY: 9a0a3c4d89msh1f5d7dc02c0c2c4p141bd5jsn15bae6ea5ff7
    networks:
      - app-net

  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: adminesraa
      POSTGRES_PASSWORD: MySecretPassword
      POSTGRES_DB: weatherapp
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
