services:

  auth:
    restart: always
    build: ./auth
    depends_on:
      - weather
    environment:
      DB_HOST: terraform-20250930092321410100000001.cryek8qkag01.eu-central-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USER: adminesraa
      DB_PASSWORD: MySecurePassword
      DB_NAME: weatherapp
      DB_SSLMODE: require
    ports:
      - "8081:8080"   # expose for local testing
    networks:
      - app-net

  ui:
    restart: always
    build: ./UI
    depends_on:
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "3000:3000"
    networks:
      - app-net

  weather:
    restart: always
    build: ./weather
    environment:
      APIKEY: 9a0a3c4d89msh1f5d7dc02c0c2c4p141bd5jsn15bae6ea5ff7
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
