apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-ui
  template:
    metadata:
      labels:
        app: weatherapp-ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/esraagaber/esraagaber/devops_weatherapp/weatherapp-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: weatherapp-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
