
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker compose build

      - name: Start services
        run: |
          docker compose up -d
          sleep 20   # wait for services to start

      - name: Run health check
        run: |
          docker ps
          curl -f http://localhost:3000 || (docker compose logs && exit 1)

      - name: Stop services
        if: always()
        run: docker compose down -v

  push-images:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert repository owner to lowercase
        id: lowercase_owner
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push : true
          tags: |
            ghcr.io/${{ env.owner }}/weatherapp-ui:latest
            ghcr.io/${{ env.owner }}/weatherapp-auth:latest
            ghcr.io/${{ env.owner }}/weatherapp-weather:latest
